# Generated by Django 5.0.14 on 2026-08-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('rule', 'Rule'), ('behavioral', 'Behavioral'), ('graph', 'Graph/Relationship'), ('model', 'Model Explanation')], max_length=16)),
                ('description', models.TextField()),
                ('structured_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='risk.riskassessment')),
            ],
        ),
    ]
