# Generated by Django 5.0.14 on 2026-08-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('system', 'System'), ('investigator', 'Investigator'), ('llm_assistant', 'LLM Assistant')], max_length=16)),
                ('action', models.CharField(max_length=64)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
