# Generated by Django 5.0.14 on 2026-08-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_score', models.FloatField(help_text='RandomForest fraud probability, scaled 0-100')),
                ('rule_score', models.FloatField(default=0, help_text='Deterministic rule engine contribution, 0-100')),
                ('behavioral_score', models.FloatField(default=0, help_text='Behavioral anomaly contribution, 0-100')),
                ('graph_score', models.FloatField(default=0, help_text='Relationship/graph anomaly contribution, 0-100')),
                ('final_score', models.FloatField(help_text='Aggregated risk score, 0-100')),
                ('risk_category', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('model_version', models.CharField(default='random_forest_v1', max_length=32)),
                ('recommended_action', models.CharField(default='monitor', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='transactions.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['risk_category'], name='risk_riskas_risk_ca_a3a1fe_idx')],
            },
        ),
    ]
